/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package posprojectuts;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import java.util.Random;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JComboBox;
import posprojectuts.Transaksi.rincian_transaksi;

/**
 *
 * @author hiskiasinaga
 */
public class POSFrame extends javax.swing.JFrame {

    ArrayList<Item> daftarItem;
    
    public static TableModel daftarModel;
    
    static int jumlahBelanja = 0;
    static Item tempItem;
    static int pilihan;
    public static boolean beliToken = false;
    /**
     * Creates new form POSFrame
     */
    
    public POSFrame() {
        DBConnector.initDBConnection();
        
//        daftarBarang = new ArrayList<Barang>();
        Barang.loadBarangFromDB();
        Makanan.loadBarangFromDB();
        Pulsa.loadBarangFromDB();
        Token.loadBarangFromDB();
        
        System.err.println(Item.daftarItem.size());
        
        daftarItem = Item.daftarItem;
        
        
        System.out.println(daftarItem.size());
        

//        Date date = new Date();
//        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
            Timer timer = new Timer(1000, e -> {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
            LocalDateTime now = LocalDateTime.now();
            String formattedDate = now.format(formatter);
            txTanggal.setText(formattedDate);
        });
        timer.start();
        initComponents();
        kodetransaksi(); //fungsi
        
        
        daftarModel = daftarTable.getModel();
daftarModel.addTableModelListener(new TableModelListener() {
    @Override
    public void tableChanged(TableModelEvent tme) {
        if (tme.getColumn() == 4) {
            int baris = tme.getFirstRow();
            Object hargaObj = daftarModel.getValueAt(baris, 3);
            Object jumlahObj = daftarModel.getValueAt(baris, 4);
            
            if (hargaObj != null && jumlahObj != null) {
                float harga = ((Float) hargaObj).floatValue();
                int jumlah = ((Integer) jumlahObj).intValue();
                
                float total = harga * jumlah;
                daftarModel.setValueAt(total, baris, 8);
                
                float totalBelanja = 0.0f;
                total = 0.0f;
                
                int jumlahBelanja = daftarModel.getRowCount(); // Assuming jumlahBelanja is the number of rows
                
                for (int i = 0; i < jumlahBelanja; i++) {
                    Object totalObj = daftarModel.getValueAt(i, 8);
                    if (totalObj != null) {
                        total = ((Float) totalObj).floatValue();
                        totalBelanja += total;
                    }
                } 
                
                int totalBelanjaInt = (int) totalBelanja;
                totalBelanjaTextField.setText(String.valueOf(totalBelanjaInt));
            }
        }
    }
}
);

    }
public static void kodetransaksi(){
        try {
            Statement stmt = DBConnector.connection.createStatement();
            String sql = "SELECT COUNT(*) as jumlah_transaksi FROM transaksi";
            ResultSet rs = stmt.executeQuery(sql);
            rs.next();
            int JumlahData = rs.getInt("jumlah_transaksi");
            System.out.println(JumlahData);
            int idtransaksi = JumlahData+2;
            String idTransString = String.format("000%03d", idtransaksi);
            id_transaksi.setText(idTransString);
        } catch (SQLException ex) {
            Logger.getLogger(POSFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        daftarTable = new javax.swing.JTable();
        kodeTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        txTanggal = new javax.swing.JTextField();
        hargaTextField = new javax.swing.JTextField();
        id_transaksi = new javax.swing.JTextField();
        NoTelpTextField = new javax.swing.JTextField();
        NoMeteranTextField = new javax.swing.JTextField();
        JenisPembayaranTextField = new javax.swing.JTextField();
        btn_bayar = new javax.swing.JButton();
        NoKartuTextField = new javax.swing.JTextField();
        BankComboBox = new javax.swing.JComboBox<>();
        totalBelanjaTextField = new javax.swing.JTextField();
        dibayarTextField = new javax.swing.JTextField();
        kembalianTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daftarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Nama", "Harga Satuan", "Jumlah", "Kadaluarsa", "Operator", "Nominal", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(daftarTable);
        if (daftarTable.getColumnModel().getColumnCount() > 0) {
            daftarTable.getColumnModel().getColumn(0).setResizable(false);
            daftarTable.getColumnModel().getColumn(0).setPreferredWidth(5);
            daftarTable.getColumnModel().getColumn(1).setResizable(false);
            daftarTable.getColumnModel().getColumn(1).setPreferredWidth(50);
            daftarTable.getColumnModel().getColumn(2).setResizable(false);
            daftarTable.getColumnModel().getColumn(2).setPreferredWidth(300);
            daftarTable.getColumnModel().getColumn(3).setResizable(false);
            daftarTable.getColumnModel().getColumn(3).setPreferredWidth(50);
            daftarTable.getColumnModel().getColumn(4).setResizable(false);
            daftarTable.getColumnModel().getColumn(4).setPreferredWidth(20);
            daftarTable.getColumnModel().getColumn(5).setResizable(false);
            daftarTable.getColumnModel().getColumn(6).setResizable(false);
            daftarTable.getColumnModel().getColumn(7).setResizable(false);
            daftarTable.getColumnModel().getColumn(8).setResizable(false);
            daftarTable.getColumnModel().getColumn(8).setPreferredWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 980, 390));

        kodeTextField.setFont(new java.awt.Font("Kristen ITC", 1, 15)); // NOI18N
        kodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(kodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 648, 200, 35));

        namaTextField.setEditable(false);
        namaTextField.setFont(new java.awt.Font("Kristen ITC", 1, 15)); // NOI18N
        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(namaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 200, 200, 35));

        txTanggal.setEditable(false);
        txTanggal.setFont(new java.awt.Font("Kristen ITC", 1, 15)); // NOI18N
        txTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTanggalActionPerformed(evt);
            }
        });
        getContentPane().add(txTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1106, 60, 210, 35));

        hargaTextField.setEditable(false);
        hargaTextField.setFont(new java.awt.Font("Kristen ITC", 1, 15)); // NOI18N
        hargaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(hargaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 289, 200, 35));

        id_transaksi.setFont(new java.awt.Font("Kristen ITC", 1, 15)); // NOI18N
        id_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_transaksiActionPerformed(evt);
            }
        });
        getContentPane().add(id_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 210, 35));

        NoTelpTextField.setEditable(false);
        NoTelpTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        NoTelpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoTelpTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NoTelpTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1405, 255, 210, 35));

        NoMeteranTextField.setEditable(false);
        NoMeteranTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        NoMeteranTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoMeteranTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NoMeteranTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1405, 528, 210, 35));

        JenisPembayaranTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        JenisPembayaranTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisPembayaranTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(JenisPembayaranTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 648, 250, 35));

        btn_bayar.setBackground(new java.awt.Color(0, 184, 107));
        btn_bayar.setFont(new java.awt.Font("ROG Fonts", 1, 18)); // NOI18N
        btn_bayar.setText("Selesai");
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 710, 200, 110));

        NoKartuTextField.setEditable(false);
        NoKartuTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        getContentPane().add(NoKartuTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1137, 785, 180, 35));

        BankComboBox.setBackground(new java.awt.Color(255, 255, 255));
        BankComboBox.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        BankComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BNI", "Mandiri" }));
        BankComboBox.setEnabled(false);
        getContentPane().add(BankComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 780, 180, 50));

        totalBelanjaTextField.setEditable(false);
        totalBelanjaTextField.setFont(new java.awt.Font("Kristen ITC", 1, 15)); // NOI18N
        totalBelanjaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBelanjaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(totalBelanjaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 648, 180, 35));

        dibayarTextField.setEditable(false);
        dibayarTextField.setFont(new java.awt.Font("Kristen ITC", 1, 15)); // NOI18N
        dibayarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayar(evt);
            }
        });
        dibayarTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dibayarTextFieldKeyReleased(evt);
            }
        });
        getContentPane().add(dibayarTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 648, 180, 35));

        kembalianTextField.setEditable(false);
        kembalianTextField.setFont(new java.awt.Font("Kristen ITC", 1, 15)); // NOI18N
        kembalianTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(kembalianTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1137, 648, 180, 35));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dashboard Background.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, 890));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void kodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeTextFieldActionPerformed
        // TODO add your handling code here:

        try {
            String kodeInput = kodeTextField.getText();       
            NoTelpTextField.setEditable(false);
            NoMeteranTextField.setEditable(false);
            NoTelpTextField.setText("");
            NoMeteranTextField.setText("");
            boolean isFound = false;
            for (int i = 0; i < daftarItem.size(); i++) {
                tempItem = daftarItem.get(i);
                if (tempItem.kode.equals(kodeInput)) {
                    if (tempItem.operator != null){
                        isFound = true;
                        System.out.println("Barang Ditemukan");
                        i = daftarItem.size();
                        namaTextField.setText(tempItem.nama);
                        hargaTextField.setText(Float.toString(tempItem.harga));
                        NoTelpTextField.setEditable(true);
                        
                    }else if(tempItem.nominal != 0){
                        isFound = true;
                        System.out.println("Barang Ditemukan");
                        i = daftarItem.size();
                        namaTextField.setText(tempItem.nama);
                        hargaTextField.setText(Float.toString(tempItem.harga));
                        NoMeteranTextField.setEditable(true);
                        
                    }else{
                        isFound = true;
                        System.out.println("Barang Ditemukan");
                        i = daftarItem.size();
                        namaTextField.setText(tempItem.nama);
                        hargaTextField.setText(Float.toString(tempItem.harga));
                        daftarModel.setValueAt(jumlahBelanja+1, jumlahBelanja, 0);
                        daftarModel.setValueAt(kodeInput, jumlahBelanja, 1);
                        daftarModel.setValueAt(tempItem.nama, jumlahBelanja, 2);
                        daftarModel.setValueAt(tempItem.harga, jumlahBelanja, 3);
                        daftarModel.setValueAt(1, jumlahBelanja, 4);
                        if(tempItem.kadaluarsa == null){
                            daftarModel.setValueAt("-------------------------", jumlahBelanja, 5);
                        }else{
                            daftarModel.setValueAt(tempItem.kadaluarsa, jumlahBelanja, 5);
                        }

                        if(tempItem.operator == null){
                            daftarModel.setValueAt("-------------------------", jumlahBelanja, 6);
                        }else{
                            daftarModel.setValueAt(tempItem.operator, jumlahBelanja, 6);
                        }

                        if(tempItem.nominal == 0){
                            daftarModel.setValueAt("-------------------------", jumlahBelanja, 7);
                        }else{
                            daftarModel.setValueAt(String.valueOf(tempItem.nominal), jumlahBelanja, 7);
                        }
                        jumlahBelanja++;
                    }
                    
                }
            }
            if (!isFound) {
                throw new Exception("Kode barang tidak ditemukan!");
            }
        } catch (NumberFormatException ex) {
            // menangani kesalahan jika pengguna memasukkan kode dalam bentuk string
            JOptionPane.showMessageDialog(null, "Kode barang harus dalam bentuk angka!");
        } catch (Exception ex) {
            // menangani kesalahan jika kode barang yang dimasukkan pengguna tidak ada
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_kodeTextFieldActionPerformed

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        String invoiceID;
        Random rand = new Random(); 
        int temp1 = rand.nextInt(10);
        int temp2 = rand.nextInt(10);
        int temp3 = rand.nextInt(10);
        int temp4 = rand.nextInt(10);
        int temp5 = rand.nextInt(10);
        int temp6 = rand.nextInt(10);
        int temp7 = rand.nextInt(10);
        int temp8 = rand.nextInt(10);
        invoiceID = String.valueOf(temp1)+String.valueOf(temp2)+String.valueOf(temp3)+String.valueOf(temp4)+String.valueOf(temp5)+String.valueOf(temp6)+String.valueOf(temp7)+String.valueOf(temp8);
      
        if (pilihan == 1){
            if (beliToken){
                int angka1 = rand.nextInt(10);
                int angka2 = rand.nextInt(10);
                int angka3 = rand.nextInt(10);
                int angka4 = rand.nextInt(10);
                int angka5 = rand.nextInt(10);
                int angka6 = rand.nextInt(10);
                int angka7 = rand.nextInt(10);
                int angka8 = rand.nextInt(10);
                int angka9 = rand.nextInt(10);
                int angka10 = rand.nextInt(10);
                int angka11 = rand.nextInt(10);
                int angka12 = rand.nextInt(10);
                int angka13 = rand.nextInt(10);
                int angka14 = rand.nextInt(10);
                int angka15 = rand.nextInt(10);
                int angka16 = rand.nextInt(10);
                int angka17 = rand.nextInt(10);
                int angka18 = rand.nextInt(10);
                int angka19 = rand.nextInt(10);
                int angka20 = rand.nextInt(10);

                Token.token = String.valueOf(angka1)+String.valueOf(angka2)+String.valueOf(angka3)+String.valueOf(angka4)+String.valueOf(angka5)+String.valueOf(angka6)+String.valueOf(angka7)+String.valueOf(angka8)+String.valueOf(angka9)+String.valueOf(angka10)+String.valueOf(angka11)+String.valueOf(angka12)+String.valueOf(angka13)+String.valueOf(angka14)+String.valueOf(angka15)+String.valueOf(angka16)+String.valueOf(angka17)+String.valueOf(angka18)+String.valueOf(angka19)+String.valueOf(angka20);

                JOptionPane.showMessageDialog(null, "Token = "+Token.token);
                beliToken = false;
            }

            String transaksitext = id_transaksi.getText();
            int inttransaksi = Integer.parseInt(transaksitext.substring(2));

            String totalBelanja = totalBelanjaTextField.getText();
            totalBelanja =totalBelanja.replace(",","");
            float TotalBelanja = Float.parseFloat(totalBelanja);


            Transaksi trans = new Transaksi(inttransaksi, TotalBelanja);

            for(int i=0; i<jumlahBelanja;i++){
                int id_barang = Integer.parseInt(daftarModel.getValueAt(i, 1).toString());
                String nama_barang = daftarModel.getValueAt(i,2).toString();
                float harga_satuan = Float.parseFloat(daftarModel.getValueAt(i,3).toString());
                int jumlah_barang = Integer.parseInt(daftarModel.getValueAt(i,4).toString());
                float harga_total = Float.parseFloat(daftarModel.getValueAt(i,8).toString());
                Transaksi.addItem(new Transaksi.rincian_transaksi(id_barang, nama_barang, harga_satuan, jumlah_barang, harga_total));
            }
            try {
            // Simpan data ke dalam database
            String strPilihan = String.valueOf(pilihan);
            Transaksi.simpanDatabase(strPilihan,invoiceID);
            // Jika berhasil, tampilkan pesan sukses
            JOptionPane.showMessageDialog(null, "Data transaksi berhasil disimpan!");
            this.dispose();
            new POSFrame().setVisible(true);
            kodetransaksi();

        } catch (SQLException ex) {
            // Jika terjadi error, tampilkan pesan error
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        jumlahBelanja = 0;
        Transaksi.listItem.clear();
        }else if (pilihan == 2){
            if (beliToken){
                int angka1 = rand.nextInt(10);
                int angka2 = rand.nextInt(10);
                int angka3 = rand.nextInt(10);
                int angka4 = rand.nextInt(10);
                int angka5 = rand.nextInt(10);
                int angka6 = rand.nextInt(10);
                int angka7 = rand.nextInt(10);
                int angka8 = rand.nextInt(10);
                int angka9 = rand.nextInt(10);
                int angka10 = rand.nextInt(10);
                int angka11 = rand.nextInt(10);
                int angka12 = rand.nextInt(10);
                int angka13 = rand.nextInt(10);
                int angka14 = rand.nextInt(10);
                int angka15 = rand.nextInt(10);
                int angka16 = rand.nextInt(10);
                int angka17 = rand.nextInt(10);
                int angka18 = rand.nextInt(10);
                int angka19 = rand.nextInt(10);
                int angka20 = rand.nextInt(10);

                Token.token = String.valueOf(angka1)+String.valueOf(angka2)+String.valueOf(angka3)+String.valueOf(angka4)+String.valueOf(angka5)+String.valueOf(angka6)+String.valueOf(angka7)+String.valueOf(angka8)+String.valueOf(angka9)+String.valueOf(angka10)+String.valueOf(angka11)+String.valueOf(angka12)+String.valueOf(angka13)+String.valueOf(angka14)+String.valueOf(angka15)+String.valueOf(angka16)+String.valueOf(angka17)+String.valueOf(angka18)+String.valueOf(angka19)+String.valueOf(angka20);

                JOptionPane.showMessageDialog(null, "Token = "+Token.token);
                beliToken = false;
            }

            String transaksitext = id_transaksi.getText();
            int inttransaksi = Integer.parseInt(transaksitext.substring(2));

            String totalBelanja = totalBelanjaTextField.getText();
            totalBelanja =totalBelanja.replace(",","");
            float TotalBelanja = Float.parseFloat(totalBelanja);


            Transaksi trans = new Transaksi(inttransaksi, TotalBelanja);

            for(int i=0; i<jumlahBelanja;i++){
                int id_barang = Integer.parseInt(daftarModel.getValueAt(i, 1).toString());
                String nama_barang = daftarModel.getValueAt(i,2).toString();
                float harga_satuan = Float.parseFloat(daftarModel.getValueAt(i,3).toString());
                int jumlah_barang = Integer.parseInt(daftarModel.getValueAt(i,4).toString());
                float harga_total = Float.parseFloat(daftarModel.getValueAt(i,8).toString());
                Transaksi.addItem(new Transaksi.rincian_transaksi(id_barang, nama_barang, harga_satuan, jumlah_barang, harga_total));
            }
            try {
            // Simpan data ke dalam database
            String strPilihan = String.valueOf(pilihan);
            Transaksi.simpanDatabase(strPilihan,invoiceID);
            // Jika berhasil, tampilkan pesan sukses
            JOptionPane.showMessageDialog(null, "Data transaksi berhasil disimpan!");
            this.dispose();
            new POSFrame().setVisible(true);
            kodetransaksi();

        } catch (SQLException ex) {
            // Jika terjadi error, tampilkan pesan error
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        jumlahBelanja = 0;
        Transaksi.listItem.clear();
        }
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void kembalianTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianTextFieldActionPerformed

    private void dibayarTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dibayarTextFieldKeyReleased
        // TODO add your handling code here:
        
        String dibayarString = dibayarTextField.getText();
        
        int dibayarInput = Integer.valueOf(dibayarString);
        
    }//GEN-LAST:event_dibayarTextFieldKeyReleased

    private void bayar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayar
try {
    String totalbelanja = totalBelanjaTextField.getText();
    float  totalBelanja = Float.valueOf(totalbelanja);
    int totalBelanjaInt = (int)totalBelanja;
    
    String bayar = dibayarTextField.getText();
    float dibayar = Float.valueOf(bayar);
    int dibayarInt = (int)dibayar;
    
    int kembalianInt = dibayarInt - totalBelanjaInt;
    kembalianTextField.setText(String.format("%,d", kembalianInt));
    if (dibayarInt < totalBelanjaInt) {
        throw new Exception("Jumlah yang dibayar kurang dari total belanja!");
    }
        Statement stmt = DBConnector.connection.createStatement();
        String sql = "INSERT INTO keuangan(total, dibayar, kembalian) VALUES('"+totalBelanjaInt+"','"+dibayarInt+"','"+kembalianInt+"')";
        stmt.execute(sql);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(null, "Masukan harus berupa angka!");
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e.getMessage());
}
    }//GEN-LAST:event_bayar

    private void totalBelanjaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBelanjaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBelanjaTextFieldActionPerformed

    private void hargaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaTextFieldActionPerformed

    private void txTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTanggalActionPerformed

    private void id_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_transaksiActionPerformed

    private void NoTelpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoTelpTextFieldActionPerformed
        // TODO add your handling code here:
        Pulsa.noTelp = NoTelpTextField.getText();
        daftarModel.setValueAt(jumlahBelanja+1, jumlahBelanja, 0);
        daftarModel.setValueAt(tempItem.kode, jumlahBelanja, 1);
        daftarModel.setValueAt((tempItem.nama+" "+Pulsa.noTelp), jumlahBelanja, 2);
        daftarModel.setValueAt(tempItem.harga, jumlahBelanja, 3);
        daftarModel.setValueAt(1, jumlahBelanja, 4);
        if(tempItem.kadaluarsa == null){
            daftarModel.setValueAt("-------------------------", jumlahBelanja, 5);
        }else{
            daftarModel.setValueAt(tempItem.kadaluarsa, jumlahBelanja, 5);
        }

        if(tempItem.operator == null){
            daftarModel.setValueAt("-------------------------", jumlahBelanja, 6);
        }else{
            daftarModel.setValueAt(tempItem.operator, jumlahBelanja, 6);
        }

        if(tempItem.nominal == 0){
            daftarModel.setValueAt("-------------------------", jumlahBelanja, 7);
        }else{
            daftarModel.setValueAt(String.valueOf(tempItem.nominal), jumlahBelanja, 7);
        }
        jumlahBelanja++;
        
    }//GEN-LAST:event_NoTelpTextFieldActionPerformed

    private void NoMeteranTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoMeteranTextFieldActionPerformed
        // TODO add your handling code here:
        beliToken = true;
        Token.noMeteran = NoMeteranTextField.getText();
        daftarModel.setValueAt(jumlahBelanja+1, jumlahBelanja, 0);
        daftarModel.setValueAt(tempItem.kode, jumlahBelanja, 1);
        daftarModel.setValueAt((tempItem.nama+" "+Token.noMeteran), jumlahBelanja, 2);
        daftarModel.setValueAt(tempItem.harga, jumlahBelanja, 3);
        daftarModel.setValueAt(1, jumlahBelanja, 4);
        if(tempItem.kadaluarsa == null){
            daftarModel.setValueAt("-------------------------", jumlahBelanja, 5);
        }else{
            daftarModel.setValueAt(tempItem.kadaluarsa, jumlahBelanja, 5);
        }

        if(tempItem.operator == null){
            daftarModel.setValueAt("-------------------------", jumlahBelanja, 6);
        }else{
            daftarModel.setValueAt(tempItem.operator, jumlahBelanja, 6);
        }

        if(tempItem.nominal == 0){
            daftarModel.setValueAt("-------------------------", jumlahBelanja, 7);
        }else{
            daftarModel.setValueAt(String.valueOf(tempItem.nominal), jumlahBelanja, 7);
        }
        jumlahBelanja++;
    }//GEN-LAST:event_NoMeteranTextFieldActionPerformed

    private void JenisPembayaranTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisPembayaranTextFieldActionPerformed
        // TODO add your handling code here:
        pilihan = Integer.valueOf(JenisPembayaranTextField.getText());
        if (pilihan == 1){
            BankComboBox.setEnabled(false);
            NoKartuTextField.setEditable(false);
            dibayarTextField.setEditable(true);
            NoKartuTextField.setText("");
            
        }else if(pilihan == 2){
            BankComboBox.setEnabled(true);
            NoKartuTextField.setEditable(true);
            dibayarTextField.setEditable(false);
            dibayarTextField.setText("");
            
        }else if(pilihan == 3){
            BankComboBox.setEnabled(false);
            NoKartuTextField.setEditable(false);
            dibayarTextField.setEditable(false);
            dibayarTextField.setText("");
            
            String invoiceID;
            Random rand = new Random(); 
            int temp1 = rand.nextInt(10);
            int temp2 = rand.nextInt(10);
            int temp3 = rand.nextInt(10);
            int temp4 = rand.nextInt(10);
            int temp5 = rand.nextInt(10);
            int temp6 = rand.nextInt(10);
            int temp7 = rand.nextInt(10);
            int temp8 = rand.nextInt(10);
            invoiceID = String.valueOf(temp1)+String.valueOf(temp2)+String.valueOf(temp3)+String.valueOf(temp4)+String.valueOf(temp5)+String.valueOf(temp6)+String.valueOf(temp7)+String.valueOf(temp8);
            
            
            
            BankComboBox.setEnabled(false);
            NoKartuTextField.setEditable(false);
            dibayarTextField.setEditable(false);
            QRIS.invoiceID = invoiceID;
            QRIS.konten = invoiceID+"TerimaKasih Telah Berbelanja";
            QRIS.QR(QRIS.konten, QRIS.invoiceID+".png");
            QRIS qris = new QRIS();
            setVisible(false);
            qris.setVisible(true);
        
            //class baru
            
        }else{
            JOptionPane.showMessageDialog(null, "Pilihan Tidak Ada!");
        }
        
    }//GEN-LAST:event_JenisPembayaranTextFieldActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSFrame().setVisible(true);
            }
        });
    }
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> BankComboBox;
    private javax.swing.JTextField JenisPembayaranTextField;
    public static javax.swing.JTextField NoKartuTextField;
    private javax.swing.JTextField NoMeteranTextField;
    private javax.swing.JTextField NoTelpTextField;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JTable daftarTable;
    private javax.swing.JTextField dibayarTextField;
    private javax.swing.JTextField hargaTextField;
    public static javax.swing.JTextField id_transaksi;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kembalianTextField;
    private javax.swing.JTextField kodeTextField;
    private javax.swing.JTextField namaTextField;
    public static javax.swing.JTextField totalBelanjaTextField;
    private javax.swing.JTextField txTanggal;
    // End of variables declaration//GEN-END:variables
}
